apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: chatgpt-telegram-bot
  name: chatgpt-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatgpt-telegram-bot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: chatgpt-telegram-bot
    spec:
      containers:
        - args:
            - python3
            - bot/bot.py
          image: chatgpt-telegram-bot
          name: chatgpt-telegram-bot
          resources: {}
      restartPolicy: Always
status: {}
